//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMVC_Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelRapor
    {
        public string Adi { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
    }
}
